//  Login Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNUP_STATUS = 'SIGNUP_STATUS';

//Service Card
export const GET_SERVICE_ACTION = 'GET_SERVICE_ACTION';
export const GET_FAVOURITE_ACTION = 'GET_FAVOURITE_ACTION';
export const GET_ALL_SERVICE = 'GET_ALL_SERVICE';
export const ADD_FAVOURITE_STATUS = 'ADD_FAVOURITE_STATUS';
export const REMOVE_FAVOURITE_STATUS = 'REMOVE_FAVOURITE_STATUS';
export const GIVING_ADD_RATING = 'GIVING_ADD_RATING';


//Profile
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const IS_SUBMITTED = 'IS_SUBMITTED';
export const SET_ISLOADING = 'SET_ISLOADING';
export const CENTER_SUCCESS = 'CENTER_SUCCESS';
export const STAFF_SUCCESS = 'STAFF_SUCCESS';
export const GET_ALL_DATE = 'GET_ALL_DATE';
export const GET_TIME_FOR_AVAILABLE_DATE = 'GET_TIME_FOR_AVAILABLE_DATE';